version: '2.1'

services:
  jaeger:
    container_name: jaeger-all
    image: jaegertracing/all-in-one:1.21
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8000}:${PORT_WEB_UI-8080}"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
